# Development environment overlay for RFID Asset Tracking System
# Version: v5.0.0
# Purpose: Extends base configuration with development-specific settings

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base configuration
bases:
  - ../../base

# Set development namespace
namespace: rfid-dev

# Development-specific labels
commonLabels:
  environment: development
  app: rfid-asset-tracking
  tier: backend
  debug-enabled: "true"

# Apply development-specific patches
patchesStrategicMerge:
  - patches/set-resources.yaml
  - patches/enable-debug.yaml
  - patches/enable-monitoring.yaml

# Development environment configuration
configMapGenerator:
  - name: rfid-config
    behavior: merge
    literals:
      - API_VERSION=v1
      - GRPC_PORT=5000
      - HTTP_PORT=3000
      - LOG_LEVEL=debug
      - ENABLE_SWAGGER=true
      - ENABLE_METRICS=true
      - DEBUG_PORT=9229
      - ENABLE_REMOTE_DEBUG=true
      - PROMETHEUS_PORT=9090
      - ENABLE_DETAILED_LOGGING=true

# Development image configurations
images:
  - name: api-gateway
    newName: rfid-asset-tracking/api-gateway
    newTag: dev
  
  - name: asset-service
    newName: rfid-asset-tracking/asset-service
    newTag: dev
  
  - name: reader-service
    newName: rfid-asset-tracking/reader-service
    newTag: dev
  
  - name: visualization-service
    newName: rfid-asset-tracking/visualization-service
    newTag: dev