# Grafana Data Sources Configuration v9.5.0
# Configures optimized data sources for RFID Asset Tracking System monitoring

apiVersion: 1

# Data sources configuration with performance-optimized settings
datasources:
  # Prometheus data source for real-time metrics monitoring
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-server:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"  # Optimized polling interval for real-time metrics
      queryTimeout: "30s"  # Configured timeout for metric queries
      httpVersion: "2"     # Using HTTP/2 for better performance
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
      customQueryParameters: ""
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.42.0"
      cacheLevel: "High"
      disableRecordingRules: false
      incrementalQueryOverlapWindow: "10m"
    secureJsonData: {}
    
  # Elasticsearch data source for log aggregation and analysis
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    version: 1
    editable: false
    database: "rfid-system-*"  # Custom index pattern for RFID system logs
    jsonData:
      timeField: "@timestamp"
      version: "7.17.0"
      maxConcurrentShardRequests: 5
      interval: "Daily"
      timeInterval: "10s"
      logMessageField: "message"
      logLevelField: "level"
      dataLinks: []
      esVersion: "7.17.0"
      timeRange: "last 15 minutes"
      includeFrozen: false
      xpack: true
      indexPattern:
        interval: "Daily"
        pattern: "rfid-system-{now/d}"
      metrics:
        - type: "count"
          field: "*"
          id: "1"
    secureJsonData: {}