apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    secret.kubernetes.io/managed-by: helm
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    rotation-schedule: monthly
    last-rotated: {{ now | date "2006-01-02" }}
type: Opaque
data:
  # Auth0 Configuration
  auth0_domain: {{ .Values.auth.auth0.domain | b64enc }}
  auth0_audience: {{ .Values.auth.auth0.audience | b64enc }}
  auth0_client_id: {{ .Values.auth.auth0.clientId | b64enc }}
  auth0_client_secret: {{ .Values.auth.auth0.clientSecret | b64enc }}

  # JWT Configuration
  jwt_secret: {{ .Values.auth.jwt.secret | b64enc }}
  jwt_expires_in: {{ .Values.auth.jwt.expiresIn | b64enc }}
  jwt_refresh_token_expires_in: {{ .Values.auth.jwt.refreshTokenExpiresIn | b64enc }}

  # PostgreSQL Database Configuration
  db_host: {{ .Values.postgresql.host | b64enc }}
  db_port: {{ .Values.postgresql.port | b64enc }}
  db_name: {{ .Values.postgresql.auth.database | b64enc }}
  db_user: {{ .Values.postgresql.auth.username | b64enc }}
  db_password: {{ .Values.postgresql.auth.password | b64enc }}
  db_connection_pool_size: {{ .Values.postgresql.pool.size | b64enc }}

  # Redis Cache Configuration
  redis_host: {{ .Values.redis.host | b64enc }}
  redis_port: {{ .Values.redis.port | b64enc }}
  redis_password: {{ .Values.redis.auth.password | b64enc }}
  redis_db_number: {{ .Values.redis.database | b64enc }}

  # InfluxDB Time-series Database Configuration
  influxdb_url: {{ .Values.influxdb.url | b64enc }}
  influxdb_token: {{ .Values.influxdb.auth.token | b64enc }}
  influxdb_org: {{ .Values.influxdb.auth.org | b64enc }}
  influxdb_bucket: {{ .Values.influxdb.auth.bucket | b64enc }}
  influxdb_retention: {{ .Values.influxdb.retention | b64enc }}

  # MinIO Object Storage Configuration
  minio_host: {{ .Values.minio.host | b64enc }}
  minio_port: {{ .Values.minio.port | b64enc }}
  minio_access_key: {{ .Values.minio.auth.rootUser | b64enc }}
  minio_secret_key: {{ .Values.minio.auth.rootPassword | b64enc }}
  minio_bucket: {{ .Values.minio.defaultBuckets | b64enc }}