# Jaeger Operator Configuration v1.45.0
# Purpose: Distributed tracing configuration for RFID Asset Tracking System
apiVersion: jaeger.jaegertracing.io/v1
kind: Jaeger
metadata:
  name: rfid-jaeger
  namespace: monitoring
  labels:
    app: rfid-tracing
    component: jaeger
spec:
  strategy: production  # Production deployment strategy for high availability

  # Storage Configuration using Elasticsearch
  storage:
    type: elasticsearch
    options:
      es.server-urls: http://elasticsearch-master:9200
      es.num-shards: 5
      es.num-replicas: 1
      es.index-prefix: rfid-traces
      es.retention: 7d
      es.bulk.size: 5000000
      es.bulk.workers: 5
      es.bulk.flush-interval: 200ms
      es.timeout: 15s

  # Sampling Configuration
  sampling:
    type: probabilistic
    options:
      default_strategy:
        type: probabilistic
        param: 1.0  # 100% sampling for comprehensive monitoring
      service_strategies:
        - service: api-gateway
          type: probabilistic
          param: 1.0
        - service: asset-service
          type: probabilistic
          param: 1.0
        - service: reader-service
          type: probabilistic
          param: 1.0
          operation_strategies:
            - operation: RFID_READ
              probabilistic:
                sampling: 1.0
        - service: visualization-service
          type: probabilistic
          param: 1.0

  # Ingress Configuration
  ingress:
    enabled: true
    security: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"

  # Agent Configuration (DaemonSet for each node)
  agent:
    strategy: DaemonSet
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m
    config:
      reporter:
        queueSize: 2000
        batchSize: 100
        batchInterval: 1s

  # Collector Configuration
  collector:
    replicas: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 1Gi
        cpu: 500m
    config:
      num-workers: 50
      queue-size: 2000
      collector:
        zipkin:
          host-port: ":9411"

  # Query Service Configuration
  query:
    replicas: 2
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 1Gi
        cpu: 500m
    config:
      query:
        base-path: /jaeger
        ui-config: 
          tracking:
            gaID: UA-000000-0
          dependencies:
            menuEnabled: true
          menu:
            - label: "About Jaeger"
              url: "https://www.jaegertracing.io"
          refresh: 5000

  # UI Configuration
  ui:
    options:
      dependencies:
        menuEnabled: true
      tracking:
        gaID: UA-000000-0
      menu:
        - label: "About RFID Tracking"
          url: "/about"
      refresh: 5000
      logoUrl: "/api/logo/rfid-logo.png"

  # Prometheus Integration
  metrics:
    backend: prometheus
    prometheusAgent:
      enabled: true
      scrapeInterval: 15s
      scrapeTimeout: 10s

  # Additional Configurations
  allInOne:
    enabled: false  # Disabled for production setup
  
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
    prometheus.io/scrape: "true"
    prometheus.io/port: "16686"

  # Security Context
  securityContext:
    runAsUser: 1000
    fsGroup: 2000

  # Service Account
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789:role/jaeger-role"

  # Volume Mounts for Certificates
  volumes:
    - name: certs
      secret:
        secretName: jaeger-tls